<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cbnetwork extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->helper(array('form', 'url', 'date'));
        $this->load->library('session', 'encrypt');	
		$this->load->library('form_validation');
        $this->load->model('Cbnetwork_model');
		HLP_is_valid_web_token();
    } 

    /*
     * Listing of internal_c_and_b_network
     */
    function index()
    {
        if(!helper_have_rights(CV_CBNETWORK, CV_VIEW_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
        $data['internal_c_and_b_network'] = $this->Cbnetwork_model->get_all_internal_c_and_b_network();
        
        $data['body'] = 'internal_c_and_b_network/index';
        $this->load->view('common/structure',$data);
    }

    /*
     * Adding a new internal_c_and_b_network
     */
    function add()
    {   
        if(!helper_have_rights(CV_CBNETWORK, CV_INSERT_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
		
		if($this->input->post())
		{
			$this->form_validation->set_rules('Name', 'Name', 'trim|required|max_length[50]');
			$this->form_validation->set_rules('Contact', 'Contact', 'trim|required|max_length[15]');
			$this->form_validation->set_rules('Email', 'Email', 'trim|required|valid_email|max_length[30]');
			$this->form_validation->set_rules('Title', 'Title', 'trim|required|max_length[150]');
			$this->form_validation->set_rules('Company', 'Company', 'trim|required|max_length[100]');
			$this->form_validation->set_rules('Industry', 'Industry', 'trim|required|max_length[100]');			
			$this->form_validation->set_rules('Country', 'Country', 'trim|required|max_length[50]');
			
			if($this->form_validation->run())
			{
				$params = array(
						'Name' => $this->input->post('Name'),
						'Title' => $this->input->post('Title'),
						'Company' => $this->input->post('Company'),
						'Industry' => $this->input->post('Industry'),
						'Country' => $this->input->post('Country'),
						'Contact' => $this->input->post('Contact'),
						'Email' => $this->input->post('Email'),
					);
				$internal_c_and_b_network_id = $this->Cbnetwork_model->add_internal_c_and_b_network($params);
				$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data save successfully.</b></div>');
				redirect('cbnetwork');				
			}
			else
			{
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>'.validation_errors().'</b></div>');
			}
			redirect('cbnetwork/add');			
		}
		
		$data['title'] = "C & B Network";
		$data['body'] = 'internal_c_and_b_network/add';
        $this->load->view('common/structure',$data);
		
		
		
		
		
        /*if(isset($_POST) && count($_POST) > 0)     
        {   if($_FILES['Document']['name'])
                {
                        $file_type = explode('.',$_FILES['Document']['name']);
                        $img_ext = strtolower($file_type[1]);

                        
                                $fName = time().".".$img_ext;
                                if (move_uploaded_file($_FILES["Document"]["tmp_name"],  "uploads/".$fName))
                                {
                                   
                                         $params = array(
                                                        'Name' => $this->input->post('Name'),
                                                        'Title' => $this->input->post('Title'),
                                                        'Company' => $this->input->post('Company'),
                                                        'Industry' => $this->input->post('Industry'),
                                                        'Country' => $this->input->post('Country'),
                                                        'Contact' => $this->input->post('Contact'),
                                                        'Email' => $this->input->post('Email'),
                                                        'Document'=>base_url()."uploads/".$fName
                                                        );
                                }
                                else
                                {
                                        $this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Document was not uploaded.</b></div>');
                                        redirect('Cbnetwork/index');
                                }
                        
                        
                }
                else {
            $params = array(
				'Name' => $this->input->post('Name'),
				'Title' => $this->input->post('Title'),
				'Company' => $this->input->post('Company'),
				'Industry' => $this->input->post('Industry'),
				'Country' => $this->input->post('Country'),
				'Contact' => $this->input->post('Contact'),
				'Email' => $this->input->post('Email'),
            );
                }
            $internal_c_and_b_network_id = $this->Cbnetwork_model->add_internal_c_and_b_network($params);
            $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data save successfully.</b></div>');
            redirect('cbnetwork/index');
        }
        else
        {            
            $data['body'] = 'internal_c_and_b_network/add';
            $this->load->view('common/structure',$data);
        }*/
    }  

    /*
     * Editing a internal_c_and_b_network
     */
    function edit($internalCBID)
    {   
         if(!helper_have_rights(CV_CBNETWORK, CV_INSERT_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
        // check if the internal_c_and_b_network exists before trying to edit it
        $data['internal_c_and_b_network'] = $this->Cbnetwork_model->get_internal_c_and_b_network($internalCBID);
        
        if(isset($data['internal_c_and_b_network']['internalCBID']))
        {
			if($this->input->post())
			{
				$this->form_validation->set_rules('Name', 'Name', 'trim|required|max_length[50]');
				$this->form_validation->set_rules('Contact', 'Contact', 'trim|required|max_length[15]');
				$this->form_validation->set_rules('Email', 'Email', 'trim|required|valid_email|max_length[30]');
				$this->form_validation->set_rules('Title', 'Title', 'trim|required|max_length[150]');
				$this->form_validation->set_rules('Company', 'Company', 'trim|required|max_length[100]');
				$this->form_validation->set_rules('Industry', 'Industry', 'trim|required|max_length[100]');			
				$this->form_validation->set_rules('Country', 'Country', 'trim|required|max_length[50]');
				
				if($this->form_validation->run())
				{
					$params = array(
							'Name' => $this->input->post('Name'),
							'Title' => $this->input->post('Title'),
							'Company' => $this->input->post('Company'),
							'Industry' => $this->input->post('Industry'),
							'Country' => $this->input->post('Country'),
							'Contact' => $this->input->post('Contact'),
							'Email' => $this->input->post('Email'),
						);
						
					$this->Cbnetwork_model->update_internal_c_and_b_network($internalCBID, $params);   
					$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data updated successfully.</b></div>');
					redirect('cbnetwork');		
				}
				else
				{
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>'.validation_errors().'</b></div>');
				}
				redirect('cbnetwork/edit/'.$internalCBID);			
			}
		
			
			$data['title'] = "C & B Network";
			$data['body'] = 'internal_c_and_b_network/edit';
            $this->load->view('common/structure',$data);
		
		
            /*if(isset($_POST) && count($_POST) > 0)     
            {   
                if($_FILES['Document']['name'])
                {
                        $file_type = explode('.',$_FILES['Document']['name']);
                        $img_ext = strtolower($file_type[1]);

                        
                                $fName = time().".".$img_ext;
                                if (move_uploaded_file($_FILES["Document"]["tmp_name"],  "uploads/".$fName))
                                {
                                   
                                         $params = array(
                                                        'Name' => $this->input->post('Name'),
                                                        'Title' => $this->input->post('Title'),
                                                        'Company' => $this->input->post('Company'),
                                                        'Industry' => $this->input->post('Industry'),
                                                        'Country' => $this->input->post('Country'),
                                                        'Contact' => $this->input->post('Contact'),
                                                        'Email' => $this->input->post('Email'),
                                                        'Document'=>base_url()."uploads/".$fName
                                                        );
                                }
                                else
                                {
                                        $this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Document was not uploaded.</b></div>');
                                        redirect('c_and_b/index');
                                }
                        
                        
                }
                else {
                $params = array(
					'Name' => $this->input->post('Name'),
					'Title' => $this->input->post('Title'),
					'Company' => $this->input->post('Company'),
					'Industry' => $this->input->post('Industry'),
					'Country' => $this->input->post('Country'),
					'Contact' => $this->input->post('Contact'),
					'Email' => $this->input->post('Email'),
                );
                }
                $this->Cbnetwork_model->update_internal_c_and_b_network($internalCBID,$params);   
                $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data updated successfully.</b></div>');
                redirect('cbnetwork/index');
            }
            else
            {
                $data['body'] = 'internal_c_and_b_network/edit';
                $this->load->view('common/structure',$data);
            }*/
        }
        else
		{
			$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>The internal c and b network you are trying to edit does not exist.</b></div>');
			redirect('cbnetwork');
		}
    } 

    /*
     * Deleting internal_c_and_b_network
     */
    function remove($internalCBID)
    {
         if(!helper_have_rights(CV_CBNETWORK, CV_INSERT_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
        $internal_c_and_b_network = $this->Cbnetwork_model->get_internal_c_and_b_network($internalCBID);

        // check if the internal_c_and_b_network exists before trying to delete it
        if(isset($internal_c_and_b_network['internalCBID']))
        {
            $this->Cbnetwork_model->delete_internal_c_and_b_network($internalCBID);
            $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data deleted successfully.</b></div>');
            redirect('cbnetwork/index');
        }
        else
            show_error('The internal_c_and_b_network you are trying to delete does not exist.');
    }
    
}
