<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Trend extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->helper(array('form', 'url', 'date'));
		$this->load->library('form_validation');
        $this->load->library('session', 'encrypt');	
        $this->load->model('Trend_model');
		HLP_is_valid_web_token();
    } 

    /*
     * Listing of trends
     */
    function index()
    {
        if(!helper_have_rights(CV_TREND, CV_VIEW_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
        $data['trends'] = $this->Trend_model->get_all_trends();
        
        $data['body'] = 'trend/index';
        $data['title'] = "C & B Trends";
        $this->load->view('common/structure',$data);
    }
    function trends()
    {
        if(!helper_have_rights(CV_TREND, CV_VIEW_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
        $data['trends'] = $this->Trend_model->get_all_trends();
        
        $data['body'] = 'trends';
        $data['title'] = "C & B Trends";
        $this->load->view('common/structure',$data);
    }
    /*
     * Adding a new trend
     */
    function add()
    {   
        if(!helper_have_rights(CV_TREND, CV_INSERT_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
            redirect(site_url("dashboard"));
		}
		
		if($this->input->post())
		{
			$this->form_validation->set_rules('Title', 'Title', 'trim|required');
			$this->form_validation->set_rules('Description', 'Description', 'trim|required');
			
			if(empty($_FILES['Document']['name']))
			{
				$this->form_validation->set_rules('Document', 'Document', 'required');
			}
			
			if($this->form_validation->run())
			{
				$upload_arr = HLP_upload_img('Document', "uploads/trends/",'',array("jpg", "jpeg", "png", "gif","pdf"));
				if(count($upload_arr) == 2)
				{ 
					$f_path = 'uploads/trends/'. $upload_arr[0];
					$params = array(
									'Title' => $this->input->post('Title'),
									'Description' => $this->input->post('Description'),
									'Document'=>base_url().$f_path
									);
					$trend_id = $this->Trend_model->add_trend($params);
            		$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data save successfully.</b></div>');
					redirect('trend');
				}
				else
				{
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>'.$upload_arr[0].'</b></div>');
				}
			}
			else
			{
				$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>'.validation_errors().'</b></div>');
			}
			redirect('trend/add');			
		}
		$data['title'] = "Trends Add";
		$data['body'] = 'trend/add';
        $this->load->view('common/structure',$data);
    }  

    /*
     * Editing a trend
     */
    function edit($TrendID)
    {   
        if(!helper_have_rights(CV_TREND, CV_INSERT_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
            redirect(site_url("dashboard"));
		}
        // check if the trend exists before trying to edit it
        $data['trend'] = $this->Trend_model->get_trend($TrendID);
        
        if(isset($data['trend']['TrendID']))
        {
			if($this->input->post())
			{
				$this->form_validation->set_rules('Title', 'Title', 'trim|required');
				$this->form_validation->set_rules('Description', 'Description', 'trim|required');
				
				if($this->form_validation->run())
				{
					$params = array(
									'Title' => $this->input->post('Title'),
									'Description' => $this->input->post('Description')
									);
					if(!empty($_FILES['Document']['name']))
					{
						$upload_arr = HLP_upload_img('Document', "uploads/trends/",'',array("jpg", "jpeg", "png", "gif","pdf"));
						if(count($upload_arr) == 2)
						{ 
							$f_path = 'uploads/trends/'. $upload_arr[0];
							$params['Document'] = base_url().$f_path;
						}
						else
						{
							$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>'.$upload_arr[0].'</b></div>');
							redirect('trend/edit/'.$TrendID);
						}
					}
					
					$this->Trend_model->update_trend($TrendID, $params);          
					$this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data updated successfully.</b></div>');
					redirect('trend/index');
					
				}
				else
				{
					$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>'.validation_errors().'</b></div>');
					redirect('trend/edit/'.$TrendID);
				}					
			}
		
			$data['body'] = 'trend/edit';
            $this->load->view('common/structure',$data);
        }
        else
		{
			$this->session->set_flashdata('message', '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>The trend you are trying to edit does not exist.</b></div>');
			redirect('trend');
		}
    } 

    /*
     * Deleting trend
     */
    function remove($TrendID)
    {
        if(!helper_have_rights(CV_TREND, CV_INSERT_RIGHT_NAME))
		{
			$data['msg'] = '<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>You do not have insert rights.</b></div>';		
                        redirect(site_url("dashboard"));
		}
        $trend = $this->Trend_model->get_trend($TrendID);

        // check if the trend exists before trying to delete it
        if(isset($trend['TrendID']))
        {
            $this->Trend_model->delete_trend($TrendID);
            $this->session->set_flashdata('message', '<div class="alert alert-success alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><b>Data deleted successfully.</b></div>');
            redirect('trend/index');
        }
        else
            show_error('The trend you are trying to delete does not exist.');
    }
    
}
