<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class C_and_b_policy_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
		$dbname = $this->session->userdata("dbname_ses");
		if(trim($dbname))
		{
			$this->db->query("Use $dbname");		
		}
    }
    
    /*
     * Get c_and_b_policy by cnbID
     */
    function get_c_and_b_policy($cnbID)
    {
        return $this->db->get_where('c_and_b_policies',array('cnbID'=>$cnbID))->row_array();
    }
        
    /*
     * Get all c_and_b_policies
     */
    function get_all_c_and_b_policies()
    {
        $this->db->order_by('cnbID', 'desc');
        return $this->db->get('c_and_b_policies')->result_array();
    }
        
    /*
     * function to add new c_and_b_policy
     */
    function add_c_and_b_policy($params)
    {
        $this->db->insert('c_and_b_policies',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update c_and_b_policy
     */
    function update_c_and_b_policy($cnbID,$params)
    {
        $this->db->where('cnbID',$cnbID);
        return $this->db->update('c_and_b_policies',$params);
    }
    
    /*
     * function to delete c_and_b_policy
     */
    function delete_c_and_b_policy($cnbID)
    {
        return $this->db->delete('c_and_b_policies',array('cnbID'=>$cnbID));
    }
}
