<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cbnetwork_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
		$dbname = $this->session->userdata("dbname_ses");
		if(trim($dbname))
		{
			$this->db->query("Use $dbname");		
		}
    }
    
    /*
     * Get internal_c_and_b_network by internalCBID
     */
    function get_internal_c_and_b_network($internalCBID)
    {
        return $this->db->get_where('internal_c_and_b_network',array('internalCBID'=>$internalCBID))->row_array();
    }
        
    /*
     * Get all internal_c_and_b_network
     */
    function get_all_internal_c_and_b_network()
    {
        $this->db->order_by('internalCBID', 'desc');
        return $this->db->get('internal_c_and_b_network')->result_array();
    }
        
    /*
     * function to add new internal_c_and_b_network
     */
    function add_internal_c_and_b_network($params)
    {
        $this->db->insert('internal_c_and_b_network',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update internal_c_and_b_network
     */
    function update_internal_c_and_b_network($internalCBID,$params)
    {
        $this->db->where('internalCBID',$internalCBID);
        return $this->db->update('internal_c_and_b_network',$params);
    }
    
    /*
     * function to delete internal_c_and_b_network
     */
    function delete_internal_c_and_b_network($internalCBID)
    {
        return $this->db->delete('internal_c_and_b_network',array('internalCBID'=>$internalCBID));
    }
}
