<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Trend_model extends CI_Model
{
    function __construct()
    {
                parent::__construct();
                $this->load->database();
		$dbname = $this->session->userdata("dbname_ses");
		if(trim($dbname))
		{
			$this->db->query("Use $dbname");		
		}
		date_default_timezone_set('Asia/Calcutta');
    }	    
    
    /*
     * Get trend by TrendID
     */
    function get_trend($TrendID)
    {
        return $this->db->get_where('trends',array('TrendID'=>$TrendID))->row_array();
    }
        
    /*
     * Get all trends
     */
    function get_all_trends()
    {
        $this->db->order_by('TrendID', 'desc');
        return $this->db->get('trends')->result_array();
    }
        
    /*
     * function to add new trend
     */
    function add_trend($params)
    {
        $this->db->insert('trends',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update trend
     */
    function update_trend($TrendID,$params)
    {
        $this->db->where('TrendID',$TrendID);
        return $this->db->update('trends',$params);
    }
    
    /*
     * function to delete trend
     */
    function delete_trend($TrendID)
    {
        return $this->db->delete('trends',array('TrendID'=>$TrendID));
    }
}
