<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Workshop_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
		$dbname = $this->session->userdata("dbname_ses");
		if(trim($dbname))
		{
			$this->db->query("Use $dbname");		
		}
    }
    
    /*
     * Get workshop by WorkshopID
     */
    function get_workshop($WorkshopID)
    {
        return $this->db->get_where('workshop',array('WorkshopID'=>$WorkshopID))->row_array();
    }
        
    /*
     * Get all workshop
     */
    function get_all_workshop()
    {
        $this->db->order_by('WorkshopID', 'desc');
        return $this->db->get('workshop')->result_array();
    }
        
    /*
     * function to add new workshop
     */
    function add_workshop($params)
    {
        $this->db->insert('workshop',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update workshop
     */
    function update_workshop($WorkshopID,$params)
    {
        $this->db->where('WorkshopID',$WorkshopID);
        return $this->db->update('workshop',$params);
    }
    
    /*
     * function to delete workshop
     */
    function delete_workshop($WorkshopID)
    {
        return $this->db->delete('workshop',array('WorkshopID'=>$WorkshopID));
    }
}
