name: CI
on:
  push:
    branches: ["main"]   
       
jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.build-image.outputs.image }}
                      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: Build, tag, and push 
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          
           
        run: |
          export PAT_php=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
          echo $PAT_php | docker login ghcr.io -u techvishal1988 --password-stdin 
          docker build -t ghcr.io/techvishal1988/php_app:$GITHUB_SHA .
          # docker push ghcr.io/techvishal1988/php_app:$GITHUB_SHA
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          echo "::set-output name=image::$GITHUB_SHA"
